branch-defaults:
  configureForAWS:
    environment: DraftAnalyzer-1b1
    group_suffix: null
global:
  application_name: Draft Analyzer
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application